spring.application.name=java_spring_mvc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/P_Shoes
spring.datasource.username=root
spring.datasource.password=Vietphap123@

# config Security
# spring.security.user.name=Vietphap123
# spring.security.user.password=123456
logging.level.org.springframework.security=DEBUG

# config view engine (JSP)
# spring.mvc.view.prefix=WEB-INF/view/
# spring.mvc.view.suffix=.jsp

# upload file
#default =1MB
spring.servlet.multipart.max-file-size=50MB
#default = 10MB (form data)
spring.servlet.multipart.max-request-size=50MB

# Spring Session
spring.session.store-type=jdbc
spring.session.timeout=30m
spring.session.jdbc.initialize-schema=always

# VNPay Configuration
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return.url=http://localhost:8080/vnpay-return
vnpay.tmn.code=OLDN7MWJ
vnpay.secret.key=W63Q3DG1KBTJ03GOFQ7QUHCV5UYADWKI
vnpay.version=2.1.0
vnpay.command=pay
vnpay.curr.code=VND
vnpay.locale=vn